import type { InferGetStaticPropsType } from "next";
import Head from "next/head";
import { SWRConfig } from "swr";
import Posts from "../components/Posts";
import { API_URL, Post } from "../lib";

const Home = ({ fallback }: InferGetStaticPropsType<typeof getStaticProps>) => {
  return (
    <div>
      <Head>
        <title>Next Swr</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="p-5">
        <SWRConfig value={{ fallback }}>
          <Posts />
        </SWRConfig>
      </main>
    </div>
  );
};

export default Home;

export async function getStaticProps() {
  const res = await fetch(API_URL);
  const posts: Post[] = await res.json();

  return {
    props: {
      fallback: {
        [API_URL]: posts.slice(0, 10),
      },
    },
  };
}
